[project]
name = "nlppp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adapters>=1.2.0",
    "ipython>=9.12.0",
    "langchain-openai>=1.1.13",
    "langgraph>=1.1.6",
    "matplotlib>=3.10.8",
    "openai>=2.31.0",
    "pandas>=3.0.2",
    "pandas-stubs>=3.0.0.260204",
    "peft>=0.19.0",
    "pyarrow>=23.0.1",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.17.1",
    "requests>=2.33.1",
    "semanticscholar>=0.12.0",
    "sentence-transformers>=5.4.0",
    "streamlit>=1.56.0",
]
