from typing import TypedDict
from qdrant_client.models import ScoredPoint


class RAGState(TypedDict):
    """
    The shared state that flows through every node in the LangGraph pipeline.

    Each node reads what it needs and writes back only what it produces.
    LangGraph merges the returned dict into the state automatically —
    nodes never need to return the full state, just their own outputs.
    """

    # The raw question as typed by the user
    original_query: str

    # The rewritten, retrieval-optimised version of the query
    rewritten_query: str
    rewritten_user_question: str

    # Top-K results returned by the Qdrant vector database.
    # Each ScoredPoint contains the paper's vector, payload (metadata like
    # abstract, title, authors), and a similarity score.
    retrieved_chunks: list[ScoredPoint]

    # Index pairs into retrieved_chunks where a contradiction was detected.
    # e.g. [(0, 2)] means chunk 0 and chunk 2 contradict each other.
    contradiction_pairs: list[tuple[int, int]]

    # The final answer generated by the LLM
    answer: str